name: optional
version: 1.2.3+1
author: Juan Antonio Ramirez <tonior@gmail.com>
description: An implementation of the Optional type
homepage: https://github.com/tonio-ramirez/optional.dart

dev_dependencies:
  test: any

  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0

